pod:
  name: ${HOSTNAME:main}

spring:
  application:
    name: chatapp

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: chatapp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_HOST}/realms/${KC_REALM_NAME}

server:
  port: 8000